// Which machine a sign-in happens on, asked rather than guessed.
//
// SCREENSHOTTED ON A TWO-HOST FLEET. The Credentials screen offered the Claude
// sign-in with no box chosen, the request went to the coordinator with no host,
// and the coordinator answered — correctly — "Which box? deb13-staging,
// deb132." The screen had no way to act on that: the refusal rendered as a
// detached card at the bottom while a three-step flow sat above it looking
// started, its footer reading "This page was generated by that machine".
//
// Both halves of the old behaviour were wrong. `absentFrom?.first ??
// hosts?.first` GUESSES, which starts a login pane on a machine nobody picked
// and sends the pasted code there; falling through to nil SENDS NOTHING, which
// produces an answer the screen cannot use. Asking is the third option, and it
// is what the rest of this project already does when a host is ambiguous.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { place } from '../src/fleet/coordinator/scheduler.js';

const read = (/** @type {string} */ p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const IOS = read('apps/ios/Fleetwright/Credentials.swift');

/** A registry with `n` connected, schedulable hosts. */
function fleet(n) {
  const hosts = Array.from({ length: n }, (_, i) => ({ hostId: `deb${i + 1}`, send: async () => ({}) }));
  return /** @type {any} */ ({
    reachable: () => hosts,
    schedulable: () => hosts,
    findSessions: () => [],
    all: () => hosts,
  });
}

test('the coordinator refuses an unaimed sign-in, and names the boxes', () => {
  // This is the behaviour the app has to cope with, and it is correct: a
  // `connect` is per-machine, so picking one would be the coordinator choosing
  // where somebody's credential gets typed.
  const refused = place(fleet(2), { verb: 'connect', params: { provider: 'claude' } });
  assert.equal(refused.kind, 'refused');
  assert.equal(refused.code, 'ambiguous_host');
  assert.match(String(refused.reason), /Which box\? deb1, deb2\./);

  // One host is not a choice, and the app must not ask about it either.
  assert.equal(place(fleet(1), { verb: 'connect', params: { provider: 'claude' } }).kind, 'host');

  // And a named host is honoured, which is what the picker produces.
  const aimed = place(fleet(2), { verb: 'connect', params: { provider: 'claude' } }, { preferHost: 'deb2' });
  assert.equal(aimed.kind, 'host');
  assert.equal(aimed.host?.hostId, 'deb2');
});

test('the app asks which machine instead of guessing one', () => {
  assert.match(IOS, /choosingHost = provider/, 'nothing presents a choice');
  assert.match(IOS, /confirmationDialog\(\s*\n?\s*"Which machine\?"/);
  // The guess is gone. `.first` on a host list is the line that sent somebody's
  // login to whichever machine the registry happened to list first.
  assert.equal(/absentFrom\?\.first \?\? connections\.hosts\?\.first/.test(IOS), false,
    'the sign-in host is still guessed from the first entry');
  // And it only asks when there is something to ask about — a picker with one
  // entry is furniture.
  assert.match(IOS, /hostsToOffer\(provider\)\.count > 1/);
});

test('both halves of the pair go to the same box', () => {
  // `connect` opens a login pane on ONE machine and `link` types the code into
  // that same pane. Step 3 was sending `host`, which is nil on the fleet-wide
  // screen — so the code was refused with "Which box?" AFTER the person had
  // left the app, signed in, and come back with a live credential in the
  // clipboard. Worse than the first failure, and the same cause.
  assert.match(IOS, /link\(host: pendingHost \?\? host/);
  // The flow records where it started, so the footer can name it rather than
  // saying "that machine" — which was written to be honest about not knowing,
  // and not knowing was itself the bug.
  assert.match(IOS, /pendingHost = chosen/);
  assert.match(IOS, /pendingHost \?\? host \?\? "that machine"/);
});

test('a refused connect leaves no flow on screen', () => {
  // A three-step form under a refusal is an invitation to finish something that
  // never began: there is no pane waiting, no URL, and nothing a code could be
  // pasted into.
  const begin = /if reply\.ok == false \{[\s\S]*?\n            \}/.exec(IOS);
  assert.ok(begin, 'begin() no longer handles a refusal');
  assert.match(begin[0], /pending = nil/);
  assert.match(begin[0], /pendingHost = nil/);
});

test('Android reaches this screen per host, so it never had the choice to make', () => {
  // Not a parity gap: the Android sheet takes a non-optional host because it is
  // opened from a host row. iOS made the screen fleet-wide — which is better,
  // and is what introduced a question Android never has to ask. Asserted so
  // that making it fleet-wide there inherits the answer rather than the bug.
  const kt = read('apps/android/app/src/main/java/network/thetech/fleetwright/CredentialsSheet.kt');
  assert.match(kt, /fun CredentialsSheet\(settings: Settings, host: String,/,
    'the Android sheet took an optional host — it now needs the picker too');
});
