import SwiftUI

/// Connecting the credentials a session needs, from a phone.
///
/// The reason this exists at all: a guest brings their own GitHub, Cloudflare
/// and Claude accounts and has no shell on any box. For them "SSH in and run
/// `claude login`" is not a smaller inconvenience — it is the whole feature
/// missing.
///
/// THE PROVIDER LIST IS NOT IN THIS FILE. It arrives from the host, with the
/// real URLs and the real scopes, and a provider added to the host's table
/// shows up here on the next refresh without an App Store release. That is the
/// entire reason the verbs are connect/link/unlink rather than one verb per
/// vendor — and it is why this view has no `switch provider` in it.
struct CredentialsView: View {
    let settings: Settings
    /// Which box to ASK. Still needed, and no longer the whole story.
    ///
    /// `connect` is a question — what could I connect, and what have I — and
    /// one box answers it for the fleet, since the catalogue is identical
    /// everywhere. A CLAUDE sign-in is genuinely per machine: it is a login
    /// the box performs in a pane, so both halves must reach the same one.
    ///
    /// A TOKEN is not. It belongs to the person, so `link` fans out to every
    /// host and this value is not sent — which is why the screen no longer
    /// says "credentials on <box>". Connecting a GitHub token again on every
    /// machine, and again on each one enrolled later, is bookkeeping the fleet
    /// exists to remove.
    let host: String

    @State private var connections = Fleet.Connections()
    @State private var pending: Fleet.Connections.Available?
    @State private var secret = ""
    @State private var result = ""
    @State private var busy = false
    @State private var loaded = false

    var body: some View {
        List {
            Section {
                ForEach(connections.catalogue) { provider in
                    row(provider)
                }
            } header: {
                Text("Your credentials")
            } footer: {
                Text("Each one is created on the provider's own page, on your account, and can be "
                     + "revoked there at any time. A token goes to every machine in the fleet, because "
                     + "it is yours rather than any one box's — sessions you start get it, and nobody "
                     + "else's do. Signing in to Claude is per machine: that one is a login the box "
                     + "performs, not a token you paste.")
            }

            if let pending {
                Section {
                    if let url = pending.url, let link = URL(string: url) {
                        Link(pending.isSignIn ? "Open the sign-in page" : "Create the token", destination: link)
                    }
                    Text(pending.hint).font(.caption).foregroundStyle(.secondary)
                    // The one field in this app that holds a live credential.
                    // Never a TextField: iOS would offer to autocorrect it,
                    // capitalise it and remember it in the keyboard cache.
                    SecureField(pending.isSignIn ? "Paste the code" : "Paste the token", text: $secret)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                    Button("Connect \(pending.label)") { Task { await link(pending) } }
                        .disabled(secret.isEmpty || busy)
                    Button("Cancel", role: .cancel) { clear() }
                } header: {
                    Text(pending.label)
                } footer: {
                    Text(pending.isSignIn
                         ? "This page was generated by \(host) for this attempt, and the code goes back to the same box."
                         : "It is checked with \(pending.label) before it is stored, so a typo fails here and not four hours into a session.")
                }
            }

            if !result.isEmpty {
                Section { Text(result).font(.callout) }
            }
        }
        .navigationTitle("Credentials")
        .task {
            guard !loaded else { return }
            loaded = true
            await load()
        }
    }

    @ViewBuilder
    private func row(_ provider: Fleet.Connections.Available) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(provider.label)
            if let linked = connections.linked(provider.provider) {
                Text(describeLinked(linked)).font(.caption).foregroundStyle(.secondary)
            } else {
                Text("not connected").font(.caption).foregroundStyle(.secondary)
            }
            HStack(spacing: 12) {
                Button(connections.linked(provider.provider) == nil ? "Connect" : "Replace") {
                    Task { await begin(provider) }
                }
                if connections.linked(provider.provider) != nil {
                    Button("Forget", role: .destructive) { Task { await forget(provider) } }
                }
            }
            .font(.caption)
            .buttonStyle(.borderless)
            .disabled(busy)
        }
        .padding(.vertical, 2)
    }

    /// Step one.
    ///
    /// A token provider already published its page in the catalogue, so there
    /// is nothing to ask the box for — the link is opened straight away. Claude
    /// has no such page: the authorization URL is minted per attempt by the CLI
    /// in a pane on that host, so the box has to be asked, and what comes back
    /// is that URL as a field rather than something scraped out of prose.
    @MainActor
    private func begin(_ provider: Fleet.Connections.Available) async {
        secret = ""
        result = ""
        guard provider.isSignIn else {
            pending = provider
            return
        }
        busy = true
        defer { busy = false }
        do {
            let reply = try await Fleet(settings: settings).connect(host: host, provider: provider.provider)
            if let fresh = reply.connections {
                connections = fresh
                pending = fresh.catalogue.first { $0.provider == provider.provider }
            }
            if reply.ok == false { result = reply.text ?? "" }
        } catch {
            result = error.localizedDescription
        }
    }

    /// Step two. The secret is cleared the moment it leaves, whether or not it
    /// worked — a failed paste is still a live credential sitting in memory
    /// behind a screen somebody is about to hand back to a colleague.
    @MainActor
    private func link(_ provider: Fleet.Connections.Available) async {
        busy = true
        defer { busy = false }
        let sending = secret.trimmingCharacters(in: .whitespacesAndNewlines)
        secret = ""
        do {
            // A token goes fleet-wide; a Claude code goes to the box whose
            // pane is waiting for it.
            let reply = provider.isSignIn
                ? try await Fleet(settings: settings).link(host: host, provider: provider.provider, secret: sending)
                : try await Fleet(settings: settings).linkEverywhere(provider: provider.provider, secret: sending)
            result = reply.text ?? ""
            if let fresh = reply.connections { connections = fresh }
            if reply.ok != false { pending = nil }
        } catch {
            result = error.localizedDescription
        }
    }

    @MainActor
    private func forget(_ provider: Fleet.Connections.Available) async {
        busy = true
        defer { busy = false }
        do {
            let reply = provider.isSignIn
                ? try await Fleet(settings: settings).unlink(host: host, provider: provider.provider)
                : try await Fleet(settings: settings).unlinkEverywhere(provider: provider.provider)
            result = reply.text ?? ""
            if let fresh = reply.connections { connections = fresh }
        } catch {
            result = error.localizedDescription
        }
    }

    @MainActor
    private func load() async {
        busy = true
        defer { busy = false }
        do {
            let reply = try await Fleet(settings: settings).connections(host: host)
            if let fresh = reply.connections { connections = fresh }
        } catch {
            result = error.localizedDescription
        }
    }

    @MainActor
    private func clear() {
        pending = nil
        secret = ""
    }
}

/// "connected as @octocat", or "connected".
///
/// A function rather than an expression in the view: a chain of `+` with
/// optional maps inside it is what made the Swift type checker give up in
/// #125, and that failure only shows up on CI.
private func describeLinked(_ linked: Fleet.Connections.Linked) -> String {
    guard let account = linked.account, !account.isEmpty else { return "connected" }
    return "connected as \(account)"
}
